### PR TITLE
#195 tabs bugs

### LINKED ISSUE #195: Make the tabs be able to work

### PR DESCRIPTION
**Pull request by Muhammad-Adam**
closes #195

### CODE REVIEW

File: app/components/home/sampleData.js [hunk 1]
```diff
@@ -1,51 +1,87 @@
...
+pastDate.setHours(nowDate.getHours() - 48);
+
 const sampleEvents = [
   {
     name: 'New Year Wild Party',
-    date: '01-01-2018',
+    dateObj: nowDate,
+    date: nowDate.toDateString(),
     venue: 'Adam\'s House',
-    description: 'Party all night at Pasir Ris!',
```
Comment (ycewe) [inline app/components/home/sampleData.js:6]: Have you tried running `gulp lint`? If I am not mistaken, it will give an error because you removed the comma at the end.

**Review by ycewe — CHANGES_REQUESTED** [review]
Please resolve conflict before I can merge

File: app/components/home/sampleData.js (hunk 1 above)
Comment (Muhammad-Adam) [reply app/components/home/sampleData.js:6]: Ouh my. I never run that before and there are alot of errors

Comment (Muhammad-Adam) [reply app/components/home/sampleData.js:6]: `const nowDate = new Date();`

They say this will give me the doublequote. How to overcome this?

Comment (ycewe) [reply app/components/home/sampleData.js:6]: Lol. I don't understand. But just google the lint error. Sure have it online.

Comment (Muhammad-Adam) [reply app/components/home/sampleData.js:6]: Almost 1k error. GG.

Comment (ycewe) [reply app/components/home/sampleData.js:6]: Solve all your errors. Check what files your edited.

Comment (Muhammad-Adam) [reply app/components/home/sampleData.js:6]: Nvm I do all the 1k errors

Comment (Muhammad-Adam) [reply app/components/home/sampleData.js:6]: I think cannot. Too many. I did all my side. Please check

Comment (Muhammad-Adam) [reply app/components/home/sampleData.js:6]: I dk how to resolve conflict leh. I never do before. :/

Comment (ycewe) [reply app/components/home/sampleData.js:6]: Cause I don't know what you need and what you don't. You can use the link below or if you use source tree, just rebase.

**Comment by Muhammad-Adam** [comment]
Changes done, please review.

**Comment by Muhammad-Adam** [comment]
@ycewe im done. Please review
